index.js, package-lock.json, package.json, test/index.js
Initial work here for review and consideration.
Please review: @bcoe @darcyclarke @ruyadorno @iansu
Thanks!
=> Initial work on parseArgs

index.js, test/index.js
Added support for multiples option and withValue option case mentioned here https://github.com/nodejs/node/pull/35015
```
**The Requirement of = for Options Expecting a Value**
For example, one may argue that --foo=bar should be the only way to use the value bar 
for the option foo; but users of CLI apps built on Node.js expect --foo bar to work just as well. 
```
Let me know if anyone thinks I should change lines 48, 58, 63 into some helper function or make it less concise and split the logic over several lines.
Thanks for the review & consideration.
=> Fleshing out parseArgs to support withValue and Multiples options

.github/workflows/ci.yaml, .nycrc, README.md, package-lock.json, package.json
Adds code coverage, configured to fail if it drops below a threshold (specified in `.nycrc`).
I've added GitHub actions to run unit tests and coverage.
Fixes #4
=> build: add code coverage and integration tests

.eslintrc, index.js, package-lock.json, package.json
adds a linter that enforces a coding style closer to Node core's.
_Note: this will make it easy to drop code directly into the codebase when the time comes._
Fixes #3
=> build: add linter to make code style closer to Node.js'

README.md, index.js, package-lock.json, test/index.js
Based on #12, and sifting through online conversations [like this](https://unix.stackexchange.com/questions/285575/whats-the-difference-between-a-flag-an-option-and-an-argument), this refactor
proposes using the terminology "args" for options that take arguments,
and "flags" for options that are boolean.
Fixes #12
=> refactor: args to flags

index.js, test/index.js
All leading dashes on options are being stripped. This was to allow `-foo` treated the same as `--foo` for some circumstances, but that approach is being reconsidered to fully support short option flags and have simple consistent behaviour.
Note: the preflight checks in current limited code mean this is only affecting two or more dashes. 
See #7 and #2
Only strip the two leading dashes of an option with two or more leading dashes.
`---foo` is parsed as an option named `-foo`.
(I followed the lint rules for the test file, rather than the local code style. I did not modify the rest of the file to pass the linter to keep this PR focused.)
=> Do not strip excess leading dashes on long option names

README.md
- remove option overwrites from repeated options (#14)
- remove array for plain values (#19)
- flags for flags, values for values (#19)
If this is acceptable, happy to update the code to behave accordingly.
=> docs: clean up README examples

index.js, test/index.js
We are proposing to determine appropriate default arguments for `node --eval`, Electron, and ES6.
Using `require.main` to determine `--eval` (or REPL) gives false positive for ES6 main program.
Related: #5 #18
Implement a placeholder for `process.mainArgs` that covers the scenarios that have been raised.
- detect `node --eval` directly by checking options passed to node (`-e`, `--eval`)
- detect `node --print` directly by checking options passed to node (`-p`, `--print`)
- no need to detect REPL because no user arguments from CLI?
- test for bundled Electron app (using same approach as Yargs and Commander)
- fallback to usual `process.argv.slice(2)`
Related PRs for Electron argument processing:
- https://github.com/tj/commander.js/pull/1172/files
- …
=> feat: expand scenarios covered by default arguments for environments

README.md
Style suggestion, no functional changes.
- change `require` to work with current package name (for now)
- change examples to follow eslint rules
- move example "output" into comments, so js block is valid javascript
(The original examples may have had the node REPL in mind with the "output" format, but I found that a bit confusing.)
=> Make README examples follow eslint rules

.eslintrc, .npmignore, README.md, index.js, package.json, primordials.js, test/index.js
Modules in Node.js use primordial helpers, so that core APIs continue working if prototypes are mutated. By moving to using this same approach it will be easier to drop this module into Node.js once ready.
I believe we will want to do some similar work as part of the resolution to #6, to make the errors we generate follow Node's conventions -- my hope is we can keep this module a direct mirror of the code in `utils/parseargs.js` (in the Node codebase).
=> refactor: use primordials

index.js
Move the code for storing parsed option to its own routine:
- simplify changes to conventions under discussion (e.g.  #19)
- simplify reuse of logic when add short options
- reduce duplicated code
The intent is zero changes in functionality, zero bugs fixes, zero changes to conventions.
=> refactor: separate out storage of parsed option in results

index.js, test/index.js
In the old parse results, `values[option]` is always an array whether or not `multiple` is used. This PR makes it so an array is not used unless the option is listed in `multiple`, in which case `values[option]` is an array from the first value added.
Fixes #19
(Code previously proposed and reviewed in #26, so will look familiar logic to some.)
Side note. `multiples` does not make the `values` start with an empty array because:
- we don't do defaults for other options
- an empty array would make detecting whether the option has been used different for a `multiple`
=> fix: only use arrays in results for multiples

README.md
We have lots of problems, but lack of subcommands is not one of them. 🤣 
Support for subcommands has not come up in issues or discussion, so not worth continuing to qualify in README. Just saying no covers it fine.
=> docs: no subcommands, no worries

README.md
We do not want `-foo` to be the same as `--foo`. That much is fairly certain.
`-foo` is likely to be the same as `-f -o -o`, at least when plain flags. But nothing implemented yet, so point to issue rather than speculate.
See #2
=> docs: clarify short options hopefully coming

index.js, test/index.js
This actually has two fixes in just two statements. They overlap, so not separate PR. :-)
The big change is always store the value for `--foo=value`, even for zero-config. See #24 for discussion to support this. This approach:
- reflects user intent
- preserves information for author curation
- does not introduce a new pattern in the shape of the result
Closes #24.
The small fix is `--foo=b=c` stores the value `b=c` (previously was ignoring text from the second equals onwards).
(Code previously proposed and reviewed in #26, so will look familiar logic to some.)
=> fix: always store value for a=b

errors.js, index.js, test/index.js, validators.js
Move to Node.js style errors and validation to make it easier to
drop into Node codebase.
Fixes #6
---
_Note: Like with primordials, this brings us closer to Node.js codebase's style._
=> refactor(errors): Node.js style validation/errors

index.js, test/index.js
Make a start on support for short options.
Handle single character short, and lookup long option in `short` configuration if present.
(Keeping code local to minimise conflicts at present. Changes still overlap with #40.)
First phase of implementing #2.
=> feat: basic support for shorts

README.md, index.js, test/index.js
We need to do "something" with a single dash, and I think it is appropriate to treat it as a positional. 
The canonical use is as per the README, a shortcut for stdin/stdout (depending on context).
(I speculate the README said "no" more because didn't want to commit to how it would be handled than because it shouldn't be a positional.)
For prior art, Commander allows single dash as a positional and also as an option value. This PR only addresses the positional, partly as less likely to be controversial, but also because less likely to conflict with other open Pull Requests!
=> feat: support single dash as positional

README.md, errors.js, index.js, test/index.js
This is a proposal for supporting short option groups that is quite simple (which I like), and at the same time agrees with an edge-case documented in `yargs-parser` -- which make me think it's a reasonable approach (_I at least haven't noticed many folks complain about this edge-case in the past_).
Quite simply, `-foo` expands out to `-f`, `-o`, `-o`, and each individual value is handled by the next step in the parser.
The interesting edge-case of this is that if `withValue` is configured for the terminal value in the short option list, and the short-option list is followed by a positional, it will be consumed:
```js
const passedArgs = ['-rf', 'foo'];
const passedOptions = { withValue: ['f'] };
const expected = { flags: { r: true, f: true }, values: { r: undefined, f: 'foo' }, …
```
=> feat(parser): support short-option groups

README.md, test/index.js
Options can come before or after positional. The option type does not matter for the example given.
(If it is an error or some snowflake result because not `withValue`, it will still behave the same for both argument orders!)
=> docs: ordering of positional and option does not matter

index.js
Fix a few typos I keep noticing (and separately from any code PR which may or may not land).
=> Fix typos in comments

README.md
Add goals and intended audience to README. This was previously buried in other places and quite likely unknown by visitors.
Copied from: https://github.com/pkgjs/parseargs/issues/52#issuecomment-1030719389
=> Add Scope to give context without wading through history

README.md, index.js, test/index.js, validators.js
Per the discussion in #45 this PR restructures the current options API where each option is configured in three separate list and instead allows options to be configured in a single object.
The goal being to make the API more intuitive for configuring options (e.g. `short`, `withValue`, and `multiples`) while creating a path forward for introducing more configuration options in the future (e.g. `default`).
Before:
```js
parseArgs(process.argv.slice(2), {
withValue: ['foo'],
multiples: ['foo'],
shorts: {
f: 'foo',
},
})
```
After:
```js
parseArgs({
args: process.argv.slice(2),
options: {
foo: {
short: 'f',
type: 'string', // defaults to 'boolean'
multiple: true,
// default: 'bar' - Future iteration
}
},
})
```
While the above mentioned discussion left off with a tentative interest in …
=> refactor!: restructure configuration to take options bag

errors.js, index.js, test/index.js, test/prototype-pollution.js, utils.js
I made a few tweaks to pass linting when creating https://github.com/nodejs/node/pull/42675 in order to pass linting.
=> refactor: tweaks for landing in Node.js

utils.js
Pulling in suggestions from @VoltrexMaster in https://github.com/nodejs/node/pull/42675
=> docs: fix formatting nits in comments

test/index.js
Per https://github.com/pkgjs/parseargs/pull/92#issuecomment-1094154140. Only one of these two PRs should land, for whichever behavior is intended.
=> add test for multiple+boolean

test/index.js
Use arrow functions for tests.
Inconsistency noted: https://github.com/nodejs/node/pull/42675#discussion_r846693999
(Pretty sure this was also noted in an older PR, but can't find the reference.)
=> refactor: use arrow functions for tests

README.md, index.js, test/index.js, test/short-option-combined-with-value.js, test/short-option-groups.js
Currently the type property is optional and defaults to boolean, but this is a bit opaque.
Closes: #94
Make it an error to leave out the type:
```js
parseArgs({
options: {
foo: { },
},
});
```
```
ERR_INVALID_ARG_TYPE [TypeError]: options.foo.type must be ('string|boolean') got undefined
```
Correct:
```js
parseArgs({
options: {
foo: { type: 'boolean' },
},
});
```
=> feat!: Require type to be specified for each supplied option

errors.js, index.js, test/index.js
Switch to using an error that already exists, to simplify merging into Node.js.
=> error: switch to existing ERR_INVALID_ARG_VALUE

test/index.js
A few more small tweaks for Node.js' linter.
=> formatting: node linter expects Error objects

test/index.js, test/utils.js
tldr; make it so we can drop `test/index.js` into `test/parallel/test-parse-args.mjs`.
----
Refactors index.js to be able to copy paste directly into the Node.js
codebase. Note: I think it is sufficient that we continue syncing just
the tests for parseArgs() to Node.js (testing the public API. This
gives us 95% coverage today, and it would be easy to push this to
100% with a couple additional tests.
Fixes #105
=> test: refactor test/index.js to match Node

README.md
Optional. Copy current proposed documentation into README so can discuss changes over PR in the usual way.
May not be considered canonical, but potentially useful!
Feel free to reject.
Closes: #107
=> docs: add upstream docs to README

index.js, test/dash.js, test/index.js, test/prototype-pollution.js, test/short-option-combined-with-value.js, test/short-option-groups.js, test/store-user-intent.js
Simple code change, with repercussions for tests and documentation. 
```
const result = {
values: { __proto__: null }, // <------- null prototype
positionals: []
};
```
Closes: #108
Removed the recently added protections when storing option values in `values` .
First cut at documentation follows. I gave two shallow examples, just pick one? I went further than the existing reference which didn't unblock my problems. (The caveats and work-arounds could go on a canonical page, if there is somewhere appropriate. I didn't go looking for that, out of scope for my current efforts!)
-----
> The `values` object returned by `parseArgs()` does not prototypically inherit from the JavaScript `Object` to avoid name clashes with your options. This means that typical `Object` methods such as …
=> feat!: create result.values with null prototype

README.md, errors.js, index.js, test/dash.js, test/index.js, test/short-option-groups.js
Fixes https://github.com/pkgjs/parseargs/issues/85.
In the second commit I've updated the message for unknown options to suggest using `--`. I'm not sure if this is worth doing, but I figured I'd implement it for discussion; happy to revert if it seems unhelpful.
=> Make positionals opt-in when strict:true

index.js, test/index.js
A couple small tweaks made while synchronizing with Node.js repository.
* small tweak to wording for greedy args (thought it read clearer).
* received warning from linter for capital Object in JSDoc.
=> nits: a couple small tweaks while merging upstream

index.js
@ljharb raised concerns in https://github.com/nodejs/node/pull/42675 that `process.defaultApp` is an electron-specific property added to `process`, and not a well known property "blessed" by Node.js itself.
I also noticed we have no tests that cover accessing `process.defaultApp`.
---
tldr; I think supporting Electron is likely a good call, and we should add this behavior back, but let's do it as a follow on PR, post landing the MVP -- rather than add any additional complexity to https://github.com/nodejs/node/pull/42675.
=> refactor!: drop handling of electron arguments

examples/simple-hard-coded.js
A pattern I use in Commander is putting all example programs from the documentation into example files with imports so they can be run straight from a checkout of the repo. I find it useful myself to check behaviour matches documentation, besides letting users try them out easily.
This PR adds an example file matching an upstream documentation example, see what you think...
(I do also add examples that don't appear in the documentation for samples of features or usage that are not covered in depth in the README, which we could do here too.)
=> docs: add example example with code from README/documentation

test/index.js
We have 100% coverage in this repo (175 tests), but have only copied up the 72 end-to-end tests in `test/index.js` which does not reach 100%. One case has been added upstream.
https://github.com/nodejs/node/pull/43358/files
(I am interested in a big refactor of the tests to make the coverage clearer, but lower hanging fruit currently!)
=> chore: add new test from upstream

README.md, examples/is-default-value.js, index.js, internal/validators.js, test/default-values.js, utils.js
The first implementation of https://github.com/pkgjs/parseargs/issues/82
This PR adds a new `default` parameter.
```js
const args = [];
const options = {
a: { type: 'string', default: 'HELLO' }
};
const result = parseArgs({ args, options }); // { values: { a: 'HELLO' } }
```
It lets the user specify an option's default value when it is not set by the `args` input.
When it is set, the `option` token is added automatically.
This pr does not include any process.env logic, but the user may set `default: process.env.WHATEVER`
=> feat: add `default` option parameter

README.md
Add versions which include support for `default` in input configuration.
=> docs: add version matchups for default

examples/optional-value.mjs
Provide an example of implementing optional option values on top of `parseArgs`.
People ask about adding this as a feature, which we do not think is appropriate in `parseArgs` due to making the parsing ambiguous. 
See:
- https://github.com/nodejs/node/issues/53427
- https://github.com/nodejs/node/pull/53434
- https://github.com/nodejs/node/issues/54396
=> docs: add example of implementing optional-value

.github/workflows/ci.yaml
=> chore: add node 20 to test matrix

internal/primordials.js
Fixes #157. This makes this library / polyfill usable on [gjs](https://gitlab.gnome.org/GNOME/gjs/) as well as any other standards compliant runtime that doesn't refer to the global object as `global`.
I also added a short comment in the copied `internal/primordials.js` to note that this modification has been made so that the header comment remains accurate.
=> fix(runtime): support runtimes without `global`
